### ISSUE TITLE
Modify the Speakers and Judges Section

### ISSUE THREAD

**Issue by vsushruth** [HackVerse/hackverse.github.io#25]
Club the Chief Guests and Speakers.
Improve the UI. 
Move this section below "Tracks" section.

**Comment by madhumithanara** [comment]
Ensure there is no picture distortion. For example, 

Non-ideal:
![image](https://user-images.githubusercontent.com/38850744/97113296-5ac8f600-170f-11eb-9ee7-92f4674b2a36.png)

Ideal:
![image](https://user-images.githubusercontent.com/38850744/97113287-471d8f80-170f-11eb-9e1f-ff3723cbe2d0.png)

**Comment by d-bugg** [comment]
I can work upon this issue

**Comment by Ackintya** [comment]
Does 

> Club the Chief Guests and Speakers.
> Improve the UI.
> Move this section below "Tracks" section.

What to improve in the UI?

**Comment by vsushruth** [comment]
Mak the UI more symmetric. Clean up the images as suggested above by Madhumita.
Change up the design. You can check these out to get an idea:
https://hackmit.org/#speakers
https://hackcbs.tech/
