### ISSUE TITLE
Layout Changes

### ISSUE THREAD

**Issue by vsushruth** [HackVerse/hackverse.github.io#26]
1. Remove "Why attend HackVerse" section.
2. Move "Sponsors" below "Chief Guest + Speaker" section. Reduce the icon sizes to make 5 sponsors in a row
3. Remove the Schedule section
4. Remove the FAQ section
5. Modify the slideshow of images in "Glimpses of the 1st Edition" such that they loop around.

**Comment by aritrasinha108** [comment]
I can take this issue up.
